name: "Subscription Vending"

on:
  repository_dispatch:
  workflow_dispatch:
  
jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Vend Subscription
        run: |
          $test = $env:TEST
          Write-Host "$test World!"
          Write-Host $env:EVENT_PAYLOAD
        shell: pwsh
        env:
          TEST: Hello
          EVENT_PAYLOAD: ${{ github.event.client_payload }}
